server:
  port: 8072
 ## servlet:
  #  context-path: /security-app
 # forward-headers-strategy: framework

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
